const entries = [
  {
    slug: "acne",
    iconKey: "acne",
    categoryKey: "conditions",
    category: "General Conditions",
    title: "Acne",
    overview: "Acne is a chronic inflammatory skin condition that can appear with blackheads, whiteheads, inflamed spots, nodules, or cystic lesions in teenagers and adults.",
    symptoms: ["Breakouts on the face, jawline, chest, shoulders, or back", "Blackheads and whiteheads", "Tender inflamed spots or deeper cysts", "Post-acne marks, discoloration, or scarring"],
    triggers: ["Hormonal shifts", "Occlusive products or heavy makeup", "Stress and sleep disruption", "Skin picking or overly aggressive routines"],
    approach: "Management often combines topical care, barrier-safe routines, anti-inflammatory treatment, scar prevention, and sometimes oral medication or procedural support depending on severity.",
    bookingAdvice: "Book when breakouts are painful, scarring starts to appear, over-the-counter care is not enough, or acne is affecting confidence and daily life.",
    related: ["Adult acne", "Acne scars", "Oily skin", "Hormonal acne"],
  },
  {
    slug: "rosacea",
    iconKey: "rosacea",
    categoryKey: "conditions",
    category: "General Conditions",
    title: "Rosacea",
    overview: "Rosacea commonly presents with persistent facial redness, flushing, visible vessels, and sensitivity. Some people also develop bumps, pustules, or eye irritation.",
    symptoms: ["Persistent redness across the cheeks or nose", "Episodes of flushing", "Visible capillaries", "Burning, stinging, or reactive skin"],
    triggers: ["Heat and sun exposure", "Alcohol or spicy foods", "Stress", "Overly active skincare or exfoliants"],
    approach: "Treatment usually focuses on calming inflammation, reducing redness, avoiding triggers, improving the barrier, and sometimes adding vascular or targeted device-based care.",
    bookingAdvice: "Book if redness becomes persistent, sensitivity worsens, or you are unsure whether the condition is rosacea, acne, dermatitis, or a mixed pattern.",
    related: ["Redness", "Sensitive skin", "Visible vessels", "Flushing"],
  },
  {
    slug: "eczema",
    iconKey: "eczema",
    categoryKey: "conditions",
    category: "General Conditions",
    title: "Eczema",
    overview: "Eczema is a barrier-related inflammatory condition linked to dryness, irritation, and recurrent itching. It may affect children or adults and often relapses over time.",
    symptoms: ["Dry, rough, itchy patches", "Redness or irritation in flexural areas", "Cracking or stinging skin", "Worsening after soaps, fragrance, or weather shifts"],
    triggers: ["Barrier disruption", "Cold weather or low humidity", "Fragrance or harsh cleansers", "Allergic or irritant exposure"],
    approach: "Management usually combines barrier repair, anti-inflammatory support during flares, trigger reduction, and long-term routine planning for prevention.",
    bookingAdvice: "Book when itching disrupts sleep, the skin becomes infected, the rash keeps recurring, or home care is no longer enough.",
    related: ["Atopic dermatitis", "Dry skin", "Itching", "Sensitive skin"],
  },
  {
    slug: "psoriasis",
    iconKey: "psoriasis",
    categoryKey: "conditions",
    category: "General Conditions",
    title: "Psoriasis",
    overview: "Psoriasis is an immune-mediated inflammatory condition that often causes well-defined plaques, scaling, and long-term recurrence on the scalp, elbows, knees, nails, or larger areas.",
    symptoms: ["Thick plaques with scale", "Scalp flaking beyond typical dandruff", "Nail changes such as pitting", "Cycles of flares and quieter periods"],
    triggers: ["Stress", "Infections or illness", "Skin trauma", "Certain medications in some cases"],
    approach: "Management may include topical treatment, scalp-focused care, systemic evaluation in moderate to severe disease, and long-term monitoring.",
    bookingAdvice: "Book when plaques spread, the scalp becomes difficult to control, joints begin to hurt, or repeated flares affect quality of life.",
    related: ["Scalp plaques", "Inflammation", "Nail psoriasis", "Scaling"],
  },
  {
    slug: "seborrheic-dermatitis",
    iconKey: "conditions",
    categoryKey: "conditions",
    category: "General Conditions",
    title: "Seborrheic Dermatitis",
    overview: "Seborrheic dermatitis is a common inflammatory condition affecting oil-rich areas such as the scalp, brows, beard area, ears, and around the nose.",
    symptoms: ["Scalp flaking or greasy scale", "Redness around the eyebrows and nose", "Itching or irritation", "Recurrent flare pattern"],
    triggers: ["Stress", "Seasonal changes", "Oil-rich skin environments", "Local sensitivity"],
    approach: "Treatment often combines anti-inflammatory support, scalp-specific cleansing, targeted maintenance routines, and facial barrier-friendly care.",
    bookingAdvice: "Book if you are unsure whether it is dandruff, psoriasis, fungal infection, or dermatitis, or if it keeps returning.",
    related: ["Dandruff", "Scalp flaking", "Redness", "Beard irritation"],
  },
  {
    slug: "fungal-infections",
    iconKey: "conditions",
    categoryKey: "conditions",
    category: "General Conditions",
    title: "Fungal Skin Infections",
    overview: "Fungal infections can affect the body, feet, groin, scalp, or nails. They are common and can mimic eczema, irritation, or psoriasis if not properly assessed.",
    symptoms: ["Circular or scaly rashes", "Persistent flaking or itching", "Toe-web irritation", "Nail thickening or discoloration"],
    triggers: ["Warm, moist environments", "Sweating and occlusion", "Shared surfaces or close contact", "Delayed treatment or misdiagnosis"],
    approach: "Management depends on body area and may include topical or oral antifungal treatment, diagnosis confirmation, and recurrence prevention.",
    bookingAdvice: "Book when a rash keeps coming back, nails become involved, or what looks like eczema is not responding.",
    related: ["Athlete's foot", "Nail fungus", "Itching", "Scaly rash"],
  },
  {
    slug: "melasma",
    iconKey: "aesthetics",
    categoryKey: "aesthetics",
    category: "Aesthetic Topics",
    title: "Melasma & Hyperpigmentation",
    overview: "Melasma and other pigment disorders often show up as uneven brown or gray patches, especially on the cheeks, forehead, upper lip, or jawline.",
    symptoms: ["Patchy facial pigmentation", "Darkening after sun exposure", "Uneven tone that returns easily", "Post-inflammatory pigment after acne or irritation"],
    triggers: ["Sun and visible light exposure", "Hormonal influences", "Heat", "Inflammation or aggressive skin treatments"],
    approach: "Successful management usually combines strict photoprotection, pigment-safe skincare, long-term maintenance, and carefully selected in-clinic procedures.",
    bookingAdvice: "Book if discoloration keeps returning, products are irritating the skin, or you want a safer structured plan.",
    related: ["Pigmentation", "Sun damage", "Post-acne marks", "Uneven tone"],
  },
  {
    slug: "sun-damage",
    iconKey: "skinTypes",
    categoryKey: "aesthetics",
    category: "Aesthetic Topics",
    title: "Sun Damage & Photoaging",
    overview: "Sun damage can affect texture, pigment, elasticity, redness, and long-term skin health. It may appear gradually and is often underestimated until more visible changes develop.",
    symptoms: ["Dark spots and uneven tone", "Rough texture", "Visible capillaries", "Fine lines and dullness"],
    triggers: ["Cumulative UV exposure", "Inconsistent sunscreen use", "Outdoor habits without protection", "Heat and environmental stress"],
    approach: "Treatment may include prevention, pigment support, resurfacing strategies, vascular support, and long-term skin quality maintenance.",
    bookingAdvice: "Book if sun spots, roughness, or redness are becoming more visible, or if you want a preventive plan before changes deepen.",
    related: ["Sun spots", "Photoaging", "Pigmentation", "Preventive care"],
  },
  {
    slug: "perioral-dermatitis",
    iconKey: "conditions",
    categoryKey: "conditions",
    category: "General Conditions",
    title: "Perioral Dermatitis",
    overview: "Perioral dermatitis is a sensitive rash pattern often seen around the mouth, nose, or eyes. It can be mistaken for acne or irritation and may flare with unsuitable products.",
    symptoms: ["Small bumps around the mouth or nose", "Burning or sensitivity", "Dryness with background redness", "Worsening after steroid use or too many actives"],
    triggers: ["Topical steroid exposure", "Heavy or occlusive products", "Overuse of exfoliants", "Barrier damage"],
    approach: "The plan usually focuses on calming the skin, stopping aggravating products, rebuilding the barrier, and treating inflammation with the right prescription approach.",
    bookingAdvice: "Book if the area keeps flaring, spreads, or has been repeatedly treated as acne without improvement.",
    related: ["Sensitive skin", "Rash around mouth", "Barrier damage", "Redness"],
  },
  {
    slug: "hives",
    iconKey: "urgent",
    categoryKey: "conditions",
    category: "General Conditions",
    title: "Urticaria & Hives",
    overview: "Hives present as raised itchy wheals that may come and go quickly or recur over time. In some cases they are short-lived; in others they become chronic.",
    symptoms: ["Raised itchy welts", "Moving or changing rash pattern", "Episodes that appear suddenly", "Swelling in some cases"],
    triggers: ["Infections or illness", "Heat, pressure, or physical triggers", "Medication reactions", "Often no clear trigger is obvious"],
    approach: "Evaluation focuses on pattern recognition, severity, recurrence, possible associated swelling, and whether a chronic urticaria strategy is needed.",
    bookingAdvice: "Book if hives keep returning, are severe, or are associated with swelling, breathing issues, or systemic symptoms.",
    related: ["Itching", "Rash", "Swelling", "Allergic reactions"],
  },
  {
    slug: "hair-loss",
    iconKey: "hair",
    categoryKey: "hair",
    category: "Hair & Scalp",
    title: "Hair Loss & Thinning",
    overview: "Hair loss can follow several patterns, including diffuse shedding, androgenetic thinning, patchy loss, or inflammation-related scalp change.",
    symptoms: ["Increased shedding during washing or brushing", "Widening part or reduced density", "Patchy hair loss", "Associated scalp irritation or scaling"],
    triggers: ["Genetic tendency", "Hormonal changes", "Stress, illness, or nutritional shifts", "Scalp inflammation"],
    approach: "Assessment often looks at shedding pattern, scalp condition, medical history, and possible contributing factors before building a long-term plan.",
    bookingAdvice: "Book early when thinning becomes noticeable or sudden shedding begins, because earlier intervention is usually more useful than waiting.",
    related: ["Scalp health", "Androgenetic loss", "Patchy loss", "Shedding"],
  },
  {
    slug: "alopecia-areata",
    iconKey: "hair",
    categoryKey: "hair",
    category: "Hair & Scalp",
    title: "Alopecia Areata",
    overview: "Alopecia areata may cause sharply defined areas of hair loss on the scalp, brows, beard, or other body hair.",
    symptoms: ["Smooth round patches of hair loss", "Sudden onset", "Brow or beard involvement", "Sometimes nail changes"],
    triggers: ["Immune-related activity", "Personal or family autoimmune background", "Stress may overlap", "Recurrence patterns vary"],
    approach: "The best approach depends on extent, speed of onset, and whether the condition is limited or recurring.",
    bookingAdvice: "Book promptly if patchy loss appears suddenly so the diagnosis can be confirmed and treatment choices can be discussed.",
    related: ["Patchy hair loss", "Autoimmune patterns", "Brows", "Scalp"],
  },
  {
    slug: "moles-skin-checks",
    iconKey: "moles",
    categoryKey: "surgery",
    category: "Surgery & Lesions",
    title: "Moles & Skin Checks",
    overview: "Skin checks are important for monitoring moles and pigmented lesions over time, especially if you have many moles, sun exposure history, or a lesion that seems to be changing.",
    symptoms: ["New mole appearance", "Shape or border changes", "Color variation", "Bleeding, irritation, or asymmetry"],
    triggers: ["Sun exposure history", "Personal risk factors", "Family history in some cases", "Lesions that evolve over time"],
    approach: "Dermatology review may include pattern assessment, dermoscopic examination, photography, follow-up timing, or biopsy/removal when needed.",
    bookingAdvice: "Book as soon as possible if a mole is changing, bleeding, asymmetrical, or feels different from your other lesions.",
    related: ["Pigmented lesions", "Dermoscopy", "Biopsy", "Prevention"],
  },
  {
    slug: "cysts-benign-lesions",
    iconKey: "surgery",
    categoryKey: "surgery",
    category: "Surgery & Lesions",
    title: "Cysts & Benign Lesions",
    overview: "Many common lumps and bumps are benign, including cysts and other ordinary lesions, but persistent or changing lesions still need proper assessment.",
    symptoms: ["Slow-growing skin bumps", "Occasional inflammation or tenderness", "Cosmetic bother or friction", "Uncertainty about what the lesion is"],
    triggers: ["Friction", "Inflammation or blockage", "Age-related benign changes", "Location-dependent irritation"],
    approach: "Management may involve observation, reassurance, removal, biopsy, or procedure planning depending on lesion type and treatment goal.",
    bookingAdvice: "Book if a lump becomes inflamed, grows, changes, or you want a clearer diagnosis before deciding on removal.",
    related: ["Cysts", "Benign lesions", "Minor procedures", "Removal"],
  },
  {
    slug: "pediatric-rashes",
    iconKey: "pediatric",
    categoryKey: "pediatric",
    category: "Pediatric",
    title: "Pediatric Rashes",
    overview: "Children can develop many rash patterns, from viral eruptions and irritant rashes to eczema or infection-related changes.",
    symptoms: ["Sudden red spots or patches", "Itching or discomfort", "Fever-associated rash in some cases", "Recurring irritation in sensitive areas"],
    triggers: ["Viral illness", "Heat or sweat", "Irritation from products or fabrics", "Underlying eczema tendency"],
    approach: "Assessment focuses on the rash pattern, age, symptoms, duration, and whether the presentation looks inflammatory, infectious, allergic, or self-limited.",
    bookingAdvice: "Book if a child's rash is spreading quickly, associated with fever, or keeps recurring without a clear explanation.",
    related: ["Child eczema", "Viral rash", "Irritation", "Heat rash"],
  },
  {
    slug: "warts-molluscum",
    iconKey: "pediatric",
    categoryKey: "pediatric",
    category: "Pediatric",
    title: "Warts & Molluscum Contagiosum",
    overview: "These common viral skin issues are especially frequent in children and may persist for months while spreading by contact or irritation.",
    symptoms: ["Small rough warts on hands or feet", "Smooth dome-shaped bumps in molluscum", "Clusters that spread with scratching", "Cosmetic worry or irritation"],
    triggers: ["Skin-to-skin contact", "Shared surfaces", "Scratching and local spread", "Sensitive or eczema-prone skin"],
    approach: "Treatment depends on age, location, discomfort, spread, and whether watchful management or more active treatment is preferred.",
    bookingAdvice: "Book if lesions are multiplying, painful, infected, or located in areas where they keep spreading.",
    related: ["Children", "Viral lesions", "Hands", "Feet"],
  },
  {
    slug: "genital-warts-hpv",
    iconKey: "venereology",
    categoryKey: "venereology",
    category: "Venereology",
    title: "HPV & Genital Warts",
    overview: "HPV-related lesions may appear as small growths or textural changes in the genital area and need proper clinical assessment for diagnosis, treatment, and follow-up.",
    symptoms: ["Small clustered growths", "Textural change in the genital area", "Sometimes no symptoms apart from visible lesions", "Recurring lesions after partial clearance"],
    triggers: ["Sexual transmission", "Local recurrence tendency", "Delayed diagnosis", "Untreated visible lesions"],
    approach: "Management may involve topical treatment, in-clinic removal methods, recurrence monitoring, and clear counseling around follow-up.",
    bookingAdvice: "Book when you notice new lesions, uncertainty in the area, or recurrence after previous treatment.",
    related: ["Venereology", "HPV", "Genital lesions", "Recurrence"],
  },
  {
    slug: "genital-herpes-irritation",
    iconKey: "venereology",
    categoryKey: "venereology",
    category: "Venereology",
    title: "Genital Herpes & Irritation",
    overview: "Pain, burning, recurrent sores, or unexplained irritation in the genital area need a careful medical approach because different conditions can look similar.",
    symptoms: ["Painful or sensitive lesions", "Burning or soreness", "Recurrent episodes", "Unexplained irritation or rash"],
    triggers: ["Viral recurrence", "Friction", "Secondary inflammation", "Incorrect self-treatment"],
    approach: "Diagnosis is the priority. Management depends on whether the concern is infectious, inflammatory, friction-related, allergic, or mixed.",
    bookingAdvice: "Book when symptoms are painful, recurring, or unclear. Proper diagnosis matters much more than guessing from internet images.",
    related: ["Venereology", "Painful lesions", "Burning", "Recurrent sores"],
  },
  {
    slug: "oily-sensitive-skin",
    iconKey: "skinTypes",
    categoryKey: "skinTypes",
    category: "Skin Types",
    title: "Oily, Sensitive, Dry, and Combination Skin",
    overview: "Skin-type education helps prevent mistakes in routines and treatments that do not match the way skin actually behaves.",
    symptoms: ["Oiliness in the T-zone or all over", "Tightness after cleansing", "Redness from common products", "Mixed areas of shine and dryness"],
    triggers: ["Using the wrong cleanser", "Seasonal changes", "Barrier damage", "Dehydration mistaken for oiliness"],
    approach: "A better routine is often built by matching cleanser strength, hydration, actives, and frequency to the skin's real response.",
    bookingAdvice: "Book if your skin reacts to nearly everything or if you want a treatment-safe routine before starting procedures.",
    related: ["Skin barrier", "Sensitive skin", "Dehydration", "Routine planning"],
  },
];

export const enContent = {
  eyebrow: "Dermatology",
  title: "Find dermatology conditions, symptoms, and care guidance",
  description: "Search by condition, symptom, or category and open detailed guidance only when you need it.",
  heroBadge: "Commonly searched topics",
  searchPlaceholder: "Search acne, itching, rosacea, moles, scalp, pigmentation...",
  stats: [
    { value: "18", label: "detailed core conditions included" },
    { value: "Searchable", label: "browse by symptom, topic, or category" },
    { value: "On demand", label: "details stay hidden until searched or opened" },
  ],
  categoryFilters: [
    { key: "all", label: "All" },
    { key: "conditions", label: "General Conditions" },
    { key: "skinTypes", label: "Skin Types" },
    { key: "pediatric", label: "Pediatric" },
    { key: "venereology", label: "Venereology" },
    { key: "surgery", label: "Surgery & Lesions" },
    { key: "aesthetics", label: "Aesthetic Topics" },
    { key: "hair", label: "Hair & Scalp" },
  ],
  bookmarksTitle: "Condition Index",
  bookmarksDescription: "These cards work as bookmarks. Click one to open that condition's guide card below, or use search to reveal matching topics.",
  guideTitle: "Condition Guides",
  guideDescription: "Each guide includes a practical overview, common symptoms, patterns or triggers, a broad treatment direction, and guidance on when it makes sense to book a consultation.",
  searchHelpTitle: "Search Tips",
  searchHelpDescription: "Try symptoms, diagnoses, body areas, or concerns such as redness, itching, acne scars, scalp flaking, melasma, or mole.",
  searchSuggestions: ["Acne", "Rosacea", "Hair loss", "Melasma", "Itching", "Mole", "Scalp", "Psoriasis"],
  currentFocusTitle: "Current Focus",
  startTitle: "Start with a search or a bookmark",
  startDescription: "Use the search bar, pick a category, or click one of the condition bookmarks above to open the detailed guide cards.",
  emptyTitle: "No matching topics found",
  emptyDescription: "Try a broader search term or switch back to All categories to see the full dermatology library.",
  sections: {
    symptoms: "Common signs and symptoms",
    triggers: "Common triggers or associated patterns",
    approach: "General treatment direction",
    booking: "When to book a consultation",
  },
  entries,
};
